wildfly/wildfly-proposals

weld/EAP7-839_CDI_2_0_support.adoc
Note that this is sent retrospectively as per request on https://issues.jboss.org/browse/EAP7-839.
E.g. the job is mostly done/merged into wfly as we speak.
=> EAP7-839 CDI 2.0 support.

management/WFCORE-3999_HttpHandler_ExtensibleHttpManagement.adoc
Issue: https://issues.jboss.org/browse/WFCORE-3999
=> [WFCORE-3999] Allow registering a custom HTTP handler for management interface

clustering/infinispan/WFLY-9648_Initial_State_Transfer.adoc
https://issues.jboss.org/browse/EAP7-888
https://issues.jboss.org/browse/WFLY-9648
=> WFLY-9648 Add ability to configure non-blocking state transfer for replicated/distributed caches

microprofile/WFLY-10709-MicroProfile-Tracing-Extension.adoc
In order to improve Observability of applications deployed in WildFly it would be beneficial to provide
transparent tracing of Java EE components via automatic initialization of a tracer (Jaeger) plus a set
of instrumentation libraries for components commonly used in Java EE applications, such as Servlets, JAX-RS, CDI, EJB, ...
This will be implemented by supporting Eclipse MicroProfile OpenTracing 1.0 for applications deployed in WildFly. The integration uses the smallrye-opentracing component to provide the MicroProfile OpenTracing implementation.
JIRA: https://issues.jboss.org/browse/WFLY-10709
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> [WFLY-10709] Observability: Support MicroProfile OpenTracing

microprofile/WFLY-10711_health_check_extension.adoc
In order to improve Observability of WildFly on OpenShift, WildFly needs
to expose health check probes
so that the container can query whether WildFly and its deployed
applications are healthy or not.
This will be implemented by supporting Eclipse MicroProfile Health 1.0
for applications deployed in WildFly.
The integration uses the smallrye-health component to provide the
MicroProfile Health implementation.
JIRA: https://issues.jboss.org/browse/WFLY-10711
=> [WFLY-10711] Observability: Support MicroProfile Health

elytron/WFCORE-3404-audit-flushing.adoc
https://issues.jboss.org/browse/WFCORE-3404
https://issues.jboss.org/browse/EAP7-1067
File-audit-endpoint needs more fine-grained log flushing configuration: to separate setting whether should be stream flushed and file descriptor synced.
=> [WFCORE-3404] Separate stream flushing and file syncing in file-audit-endpoint

elytron/WFLY-10810_Elytron_JASPI_Servlet_Profile_Support.adoc
This replaces the analysis previously being tracked at https://developer.jboss.org/wiki/AnalysisDesign-JASPICIntegrationWithWildFlyElytron
=> [WFLY-10810] Add JASPI support to WildFly Elytron.

microprofile/WFLY-11529_subsystem_metrics.asciidoc
Proposal to expose metrics from WildFly subsystem and deployments to the
`/metrics` HTTP endpoint in the Prometheus format to be able to be
consumer and aggregate by Prometheus.
JIRA: https://issues.jboss.org/browse/WFLY-11529
=> [WFLY-11529] Expose WildFly metrics

console/EAP7-1129_Add_support_for_JASPI.adoc
https://issues.jboss.org/browse/EAP7-1129
=> EAP7-1129 Add support for JASPI as added to the WildFly Elytron Subsystem

build/WFCORE-3769_WFLY-10305_galleon_build.adoc
https://issues.jboss.org/browse/WFCORE-3769
https://issues.jboss.org/browse/WFLY-10305
Proposal for converting the WildFly (Core) build to use Galleon in WildFly 13.
This is the first step in the shift to Galleon. It's not really a feature per se, as it is an internal detail of how we build. But it's useful to have the details specified.
I put some stuff in the "Test Plan" section which is beyond my remit I suppose. My intent there is to share some concepts.
I authored this initial effort on behalf of @aloubyansky but this is really his proposal; i.e. he's the main person to address any inputs.
=> [WFCORE-3769][WFLY-10305] Use Galleon for the build

messaging/WFLY-11829_artemis_clusters_with_http_load_balancer.adoc
* Adding a new attribute in 'all' cf and pcf to avoid sending the internal cluster topology to the clients.
Jira: https://issues.jboss.org/browse/WFLY-11829
=> [WFLY-11829]: Support messaging clusters (Artemis Clusters) behind http load balancers.

microprofile/WFLY-12294_upgrade_microprofile-metrics_2.0.1.adoc
Dev analysis to upgrade MicroProfile Metrics to 2.0.1
JIRA: https://issues.jboss.org/browse/WFLY-12294
=> [WFLY-12294] Upgrade MicroProfile Metrics 2.0.1

elytron/WFCORE-4447-realm-aggregation-for-attributes.adoc
https://issues.jboss.org/browse/WFCORE-4447
=> [WFCORE-4447] Adding support to load an identity's attributes using multiple security realms.

messaging/WFLY-11293_add_attribute_to_indicate_backup_is_synchronized.adoc
* adding a `synchronized-with-live` attribute on `/subsystem=messaging-activemq/server=default/ha-policy=replication-slave`
* adding a `synchronized-with-backup` attribute on `/subsystem=messaging-activemq/server=default/ha-policy=replication-master`
Jira: https://issues.jboss.org/browse/WFLY-11293
=> [WFLY-11293]: Add attribute to model which will indicate that backup is synchronized with live server.

jaxrs/WFLY-11737_http_proxy.adoc
https://issues.jboss.org/browse/WFLY-11737
https://issues.jboss.org/browse/RESTEASY-1952
=> RESTEasy support for setting HTTP proxy by using JAX-RS API

design-doc-template.adoc
Ease the WildFly release process by encouraging proposal authors to provide draft short text for an entry in the Release Note blog article.
=> Add a Release Note section to the proposal template

openshift/CLOUD-2262.adoc
https://issues.jboss.org/browse/EAP7-1192
https://issues.jboss.org/browse/CLOUD-2262
[The design document](https://github.com/ochaloup/wildfly-proposals/blob/EAP7-1192-openshift-ejb-txn-propagation/openshift/CLOUD-2262.adoc) for the EAP7-1192/CLOUD-2262. It needs to be review by @tadamski and it could be good to be checked by @fmarchioni
=> [CLOUD-2262][EAP7-1192] txn propagation over ejb remoting on OpenShift

ee/WFLY-1160-Provide_ability_to_configure_a_global_directory_which_puts_the_contents_in_the_classpath.adoc
An RFE to allow the configuration of external folders with libraries shared across all deployments without specifying global modules.
Jira issue: https://issues.jboss.org/browse/WFLY-1160
=> [WFLY-1160] Provide ability to easily apply certain JBoss module libraries to all deployments running in a server

microprofile/WFLY-13023_upgrade_microprofile-config_1.4.adoc
JIRA: https://issues.redhat.com/browse/WFLY-13023
=> [WFLY-13023] Upgrade MicroProfile Config 1.4

microprofile/WFLY-13048_upgrade_microprofile-health_2.2.adoc
* add dev analysis to upgrade MicroProfile Health to 2.2 (as part of
MicroProfile 3.3)
JIRA: https://issues.redhat.com/browse/WFLY-13048
=> [WFLY-13048] Upgrade MicroProfile Health 2.2

messaging/WFLY-9513_messaging_jdbc_HA_shared-store.adoc
Proposal to support Artemis HA in JDBC Store by the messaging-activemq
subsytem.
JIRA: https://issues.jboss.org/browse/WFLY-9513
=> [WFLY-9513] Support Messaging JDBC HA Shared Store

jpa/WFLY-12674_wildfly.jpa.skipquerydetach.adoc
https://issues.jboss.org/browse/WFLY-12674
https://issues.jboss.org/browse/EAP7-1365
=> WFLY-12674 wildfly.jpa.skipquerydetach set to true, will now skip clearing of query results

elytron/WFCORE-4485-multiple-security-realms-distributed-identities.adoc
https://issues.redhat.com/browse/WFCORE-4485
=> [WFCORE-4485] Support for multiple security realms - Distributed Identities

microprofile/WFLY-12342_server_readiness_probes.adoc
Dev analysis for WFLY-12342
JIRA: https://issues.jboss.org/browse/WFLY-12342
=> [WFLY-12342] Add server probes for readiness health check

elytron/WFCORE-4842-tls-1.3-with-openssl.adoc
https://issues.redhat.com/browse/WFCORE-4842
=> [WFCORE-4842] Add support for TLS 1.3 using the OpenSSL TLS provider with Elytron

elytron/WFCORE-4484-ssh-authentication-git-persistence.adoc
https://issues.jboss.org/browse/WFCORE-4484
https://issues.jboss.org/browse/EAP7-1213
https://issues.jboss.org/browse/ELY-1879
https://issues.jboss.org/browse/WFLY-12574
=> [WFCORE-4484] Support SSH Authentication for Git persistence

elytron/WFCORE-4994-case-principal-transformer.adoc
https://issues.redhat.com/browse/WFCORE-4994
=> WFCORE-4994 Add the ability to adjust the case of a user name using an Elytron principal transformer

elytron/WFLY-13706-keycloak-feature-pack.adoc
As described in the analysis this new feature pack is to be provided from the Keycloak project, however as it's target audience is exclusively users of WildFly this analysis is considering the feature pack from that perspective.
https://issues.redhat.com/browse/WFLY-13706
=> [WFLY-13706] New feature pack to make the Keycloak client adapters provisionable using Galleon.

ee/WFCORE-4135_Support_for_ read_only_server_config_dir.adoc
This supersedes https://github.com/wildfly/wildfly-proposals/pull/304
A proposal to use read only server configuration dir
Jira issue: https://issues.redhat.com/browse/WFCORE-4135
Hello @OndrejKotek , as discussed I dropped from the analysis the notes about the required changes for cloud images. If you are fine with the current content and has no further questions, would you mind approving it? thanks
=> [WFCORE-4135] Support for read only server configuration directory

concurrency/WFLY-12896_EE_Concurrency_Hung_Tasks_Termination.adoc
Issue: https://issues.jboss.org/browse/WFLY-12896
=> [WFLY-12896] EE Concurrency Hung Tasks Termination

elytron/WFCORE-4360-CredentialStore_Expression_Resolution.adoc
This pull request supersedes https://github.com/wildfly/wildfly-proposals/pull/213
This analysis discusses the resources and utilities that will be provided to support the encryption of expressions in the management model.
https://issues.jboss.org/browse/EAP7-677
https://issues.jboss.org/browse/WFCORE-4360
At this point in time unless there are problems in the late stages if implementation it is not expected that the details will diverge too fat from this analysis.
=> [WFCORE-4360] Support expression resolution backed by a CredentialStore.

quickstarts/WFLY-14563_todo-backend-quickstart.adoc
Add a new quickstart todo-backend to showcases a typical use of
WildFly: a backend that exposes a Web API (using JAX-RS) and connects to
a DB (using JPA).
The quickstart focuses on local and cloud deployment with Bootable Jar
and showcase the following features:
* use the wildfly-datasources-galleon-pack to connect to an external
PostgreSQL database
* Execute a CLI script at build time to specialize the WildFly runtime
provisioned by the Bootable Jar
* Use of Helm Charts for cloud deployment
JIRA: https://issues.redhat.com/browse/WFLY-14563
=> [WFLY-14563] todo-backend quickstart

elytron/WFCORE-5027-charset-encoding-support.adoc
https://issues.redhat.com/browse/WFCORE-5027
=> [WFCORE-5027] Adding a proposal for charset and encoding support for credentials in security realms

elytron/WFCORE-5145-ssl-allowed-protocols.adoc
https://issues.redhat.com/browse/WFCORE-5145
=> [WFCORE-5145] Add a proposal about adding support for the SSLv2Hello protocol

microprofile/WFLY-14798-upgrade-reactive-messaging-2.0.adoc
https://issues.redhat.com/browse/WFLY-14798
=> [WFLY-14798] Upgrade to Reactive Messaging 2.0

jaxrs/WFLY-14812-resteasy-4-upgrade.adoc
https://issues.redhat.com/browse/WFLY-14812
=> [WFLY-14812] Migrate RESTEasy from 3.x to 4.x

microprofile/WFLY-14987_reactive_messaging-ssl-context-kafka-connector.adoc
https://issues.redhat.com/browse/WFLY-14987
=> [WFLY-14987] Use Elytron SSLContext to connect to secure Kafka

observability/WFLY-14854_add_opentelemetry_support.adoc
https://issues.redhat.com/browse/WFLY-14854
=> [WFLY-14854] Analysis document for OpenTelemetry support

maven/WFLY-14934_Server_Plugin.adoc
* This is an evolution of the initial proposal with some changes that are added to the WildFly Maven plugin allowing for minimal developer workflow.
* In addition, the property ``layers-configuration-file-name`` has been added allowing to integrate the maven plugin in wildfly tests. This update of the proposal documents it.
=> Proposal for WFLY-14934, WildFly server Maven plugin [adjustments for basic developer workflow]

observability/WFLY-14947-Implement_observability_policy_metrics.adoc
https://issues.redhat.com/browse/WFLY-14947
Create analysis doc
=> [WFLY-14947] Create analysis doc for Micrometer Support

jaxrs/WFLY-17020-resteasy-6.2-upgrade.adoc
https://issues.redhat.com/browse/WFLY-17020
Signed-off-by: James R. Perkins <jperkins@redhat.com>
=> [WFLY-15695] Migrate RESTEasy from 4.x to 6.2

security/WFCORE-5526_Remove_Legacy_Security_Realms.adoc
https://issues.redhat.com/browse/WFCORE-5526
=> [WFCORE-5526] Remove Legacy Security Realms from WildFly Core and WildFly.

elytron/ELY-1211_FileAuditEndpoint_configure_encoding.adoc
https://issues.redhat.com/browse/EAP7-1557
https://issues.redhat.com/browse/ELY-1211
https://issues.redhat.com/browse/WFCORE-5106
=> [ELY-1211] FileAuditEndpoint doesn't allow for file encoding to be overridden

elytron/WFCORE-5740-ability-to-ignore-unavailable-realms-for-a-distributed-realm.adoc
https://issues.redhat.com/browse/EAP7-1862
https://issues.redhat.com/browse/WFCORE-5740
https://issues.redhat.com/browse/ELY-2305
=> [WFCORE-5740] Add the ability to ignore unavailable realms for a distributed-realm

elytron/WFLY-15260_oidc_management_console.adoc
https://issues.redhat.com/browse/WFLY-15260
=> [WFLY-15260] Support for securing the management console with OIDC

core/WFCORE-4758_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
Exporting a runtime server configuration as an XML file.
Jira: https://issues.redhat.com/projects/WFCORE/issues/WFCORE-4758
=> [WFCORE-4758]: Simple config export for a server as an attachment for standalone or domain mode

microprofile/WFLY-17137-microprofile-jakarta-ee-10.adoc
https://issues.redhat.com/browse/WFLY-17137
This is the original proposal document, and targets MP Platform 6.0. #537 contains adjustments, in case we are in a position to support MP Platform 6.1.
=> [WFLY-17137] MicroProfile with Jakarta EE10

ee/WFLY-18838_Preview_support_for_Jakarta_MVC_2.1.adoc
https://issues.redhat.com/browse/WFLY-18838
See also https://github.com/wildfly-extras/mvc-krazo-feature-pack
=> [WFLY-18838] Preview support for Jakarta MVC 2.1

build/WFLY-19130_publish_Wildfly_channel_manifest.adoc
Issue: https://issues.redhat.com/browse/WFLY-19130
=> [WFLY-19130] Publish Wildfly channels

elytron/WFLY-16532-additional-scope-for-auth-request.adoc
https://issues.redhat.com/browse/WFLY-16532
=> [WFLY-16532] Preview - Add the ability to configure additional scope values for an authentication request

controller/WFCORE-4868_configuration-files-aliases.adoc
Issue: [EAP7-1700](https://issues.redhat.com/browse/EAP7-1700) / [WFCORE-4868](https://issues.redhat.com/browse/WFCORE-4868)
=> WFCORE-4868 Introduce aliases for standard configuration files

wf-galleon/WFLY-19021-Stability_In_Provisioning.adoc
Proposal for Issue: https://issues.redhat.com/browse/WFLY-19021
=> [Community] Proposal for WFLY-19021, Stability support in WildFly provisioning

user-experience/WFLY-18428_get_started_with_wildfly.adoc
Proposal to improve the get started experience with WildFly, its related resources and changes to the wildfly.org web site to promote a fresh modern way to develop Entreprise Java applications with WildFly.
JIRA: https://issues.redhat.com/browse/WFLY-18428
=> [WFLY-18428] Improve the 'Get Started' Experience with WildFly

.github/workflows/check_process.yml, .scripts/check_proposals
=> [#568] Add GitHub action to verify the front matter metadata

core/WFCORE-5343_Support_YAML_files_for_configuration_customization.adoc
Supersedes https://github.com/wildfly/wildfly-proposals/pull/381
=> [WFCORE-5343]: Proposal for YAML support

cloud/WFLY-Operator-100-report-txn-heuristic-state-better.adoc
https://github.com/wildfly/wildfly-operator/issues/100
https://issues.redhat.com/browse/EAP7-1394
=> [WFL-Operator-100] adding a way to report heuristic transaction state during scaledown

migration/CMTOOL-284_JBoss_EAP_7.4_Server_Migration_Tool.adoc
Issue: https://issues.redhat.com/browse/CMTOOL-284
=> CMTOOL-284: JBoss EAP 7.4 Server Migration Tool

security/WFLY-15199_Remove_Legacy_Security_Subsystem.adoc
This is the initial analysis for the removal of the legacy security subsystem.
https://issues.redhat.com/browse/WFLY-15199
=> [WFLY-15199] Add analysis for the removal of the legacy security subsystem.

microprofile/WFLY-17510-remove-microprofile-opentracing.adoc
https://issues.redhat.com/browse/WFLY-17510
Analysis doc for MP OpenTracing Removal
=> [WFLY-17510] Convert MicroProfile OpenTracing subsystem to Admin-Only Mode

transactions/WFLY-14869-microprofile-lra.adoc
https://issues.redhat.com/browse/WFLY-14869
=> WFLY-14869 Add support for MicroProfile LRA

console/HAL-1832_Activate_OIDC.adoc
https://issues.redhat.com/browse/HAL-1832
=> [HAL-1832] Activate OIDC in the console

server/WFCORE-6750-unstable-api-annotation-scanner.adoc
https://issues.redhat.com/browse/WFCORE-6750 (the runtime scanner)
https://issues.redhat.com/browse/WFLY-19152 (creating the indices in the feature pack build)
=> [WFCORE-6750] Analysis document for the Unstable API Annotation scanning

elytron/WFLY-17143-request-uri-parameters.adoc
Issue: https://issues.redhat.com/browse/WFLY-17143
related issue: https://issues.redhat.com/browse/ELY-2584
Relevant github discussions: 
- https://github.com/keycloak/keycloak/discussions/23150
- https://github.com/keycloak/keycloak/discussions/22729
- https://github.com/keycloak/keycloak/discussions/24514
=> [WFLY-17143] Preview - Add the ability to specify that the OIDC Authentication Request should include request and request_uri parameters

undertow/WFLY-14255_Make_resuseXForwarded_and_rewriteHost_configurable.adoc
https://issues.redhat.com/browse/WFLY-14255
=> [WFLY-14255] Make reuseXForwarded and rewriteHost configurable

FEATURE_PROCESS.adoc
As discussed in process and tracking tool discussion, port Brian's table to adoc format in this repo
=> [feature_file] Create feature process file

core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
Jira: https://issues.redhat.com/browse/WFCORE-6960
=> [WFCORE-6960]: Promote Simple config export for a server as an attachment from COMMUNITY to DEFAULT.

.gitignore, FEATURE_PROCESS.adoc, design-doc-template.adoc
The updates I am proposing here relate to how in general the admin clients should be considered when new features are added to the application server.
The admin clients are maintained by smaller teams within the overall WildFly team, for this reason it is not going to scale if every feature requires complete admin client integration at every stability level so the general premise behind this proposal is that features can be added at Experimental or Preview level with a reduced set of admin client requirements, the admin clients can then continue to evolve to add these features and then the underlying feature can be promoted to Community / Default.
Note: This is not so much about features being added directly to the admin clients at the stability levels as in that case the admin client …
=> Add admin client requirements to the process

design-doc-template.adoc
F2F: WildFly Community Feature Test Plan
Note this is an initial draft for these changes, wider input is more than welcome!
FYI: @yersan @OndrejKotek @ehsavoie
=> Test plan updates & stability levels

design-doc-template.adoc
@bstansberry @darranl After lengthy discussions with @fabiobrz and @marekkopecky about manual testing, I have realized that part of the manual verification we do for every MicroProfile related RFE and that cannot be automated, is testing a corresponding existing quick start. Here's a suggestion to add this to the template so that people are reminded to do that and add that to the list (case in point, I forgot about it). Note this doesn't only pertain to MP, we have recently used a quickstart to validate clustering RFEs.
=> Feature process template doc: add quickstarts as typical test to include in manual testing.

microprofile/WFLY-19591_MicroProfile_OpenAPI_4.0.adoc
https://issues.redhat.com/browse/WFLY-19591
=> WFLY-19591 MicroProfile OpenAPI 4.0

microprofile/WFLY-19954_Preview_Support_vertx_feature_pack.adoc
=> [WFLY-19954] Add the vertx extension/subsystem from wildfly-vertx-feature-pack to WildFly Preview Feature Pack

observability/WFLY-19846-promote-mp-tel-2-to-default.adoc
Add analysis document
Resolves https://github.com/wildfly/wildfly-proposals/issues/619
=> [WFLY-19846] Migrate MP Tel 2.0 from PREVIEW to DEFAULT

wf-galleon/WFLY-19855_glow_spaces.adoc
=> [WFLY-19855] WildFly Glow, introduce spaces to structure discovered Galleon feature-packs

.scripts/check_proposals
* fail if the YAML front matter is not present or not a valid YAML block
* fail if the files can not be read
=> Improve the check proposal scripts

design-doc-template.adoc
Just new line to separate metadata and TOC. Some editors are tad more strict or too strict and will swallow first paragraph of TOC.
=> Add \n between metadata table and TOC syntax start

observability/WFLY-18582_add-prometheus-endpoint-to-micrometer-extension.adoc
https://issues.redhat.com/browse/WFLY-18582
Add analysis document
Resolves https://github.com/wildfly/wildfly-proposals/issues/590
=> [WFLY-18582] Add prometheus endpoint to micrometer extension
