jsf/WFLY-6462_JSF_2.3.adoc

https://issues.jboss.org/browse/WFLY-6462
https://issues.jboss.org/browse/EAP7-893

WFLY-6462 JSF 2.3 Support

---

bv/WFLY-9628_EAP7-907_Bean-Validation_2.0.adoc

* https://issues.jboss.org/browse/EAP7-907
* https://issues.jboss.org/browse/WFLY-9628
* https://github.com/wildfly/wildfly/pull/10725

WFLY-9628 EAP7-907 Bean Validation 2.0 support

---

undertow/WFLY-6456_Servlet_4.0.adoc

https://issues.jboss.org/browse/EAP7-902
https://issues.jboss.org/browse/WFLY-6456

WFLY-6456 Servlet 4.0

---

WFLY-6459_EAP7-838_JAX-RS_2.1.adoc

https://issues.jboss.org/browse/EAP7-838
https://issues.jboss.org/browse/WFLY-6459

WFLY-6459 / EAP7-838 JAX-RS 2.1 support

---

WFLY-9825-microprofile-rest-client-1.0.adoc

https://issues.jboss.org/browse/WFLY-9825

[WFLY-9825] MP REST Client 1.0 dev analysis

---

WFLY-9787_EAP7-843_JAXRS_client_redirect.adoc

https://issues.jboss.org/browse/WFLY-9787
https://issues.jboss.org/browse/EAP7-843

WFLY-9787 / EAP7-843 JAXRS client redirect

---

EAP7-912.adoc

https://issues.jboss.org/browse/WFLY-6458

[WFLY-6458] Add analysis documentation for JavaMail 1.6

---

WFLY-9786_EAP-886_RESTEasy-JDK9.adoc

https://issues.jboss.org/browse/EAP7-886
https://issues.jboss.org/browse/WFLY-9786

[WFLY-9786] RESTEasy JDK9

---

jca/WFLY-5603_DataSource_Class_Information.adoc

https://issues.jboss.org/browse/WFLY-5603
https://issues.jboss.org/browse/EAP7-940

[WFLY-5603] Get data source information

---

clustering/jgroups/WFLY-9563_Integrate_KUBE_PING_Discovery_Protocol.adoc

https://issues.jboss.org/browse/WFLY-9563
https://issues.jboss.org/browse/EAP7-861

WFLY-9563 Integrate KUBE_PING discovery protocol

---

cli/EAP7-924_Coloured_output_for_CLI.adoc

Issue: https://issues.jboss.org/browse/EAP7-924

[EAP7-924] Coloured output for CLI

---

embedded/WFCORE-3205-embedded-logging.adoc

https://issues.jboss.org/browse/WFCORE-3205

[WFCORE-3205] Design document/requirements for fixing embedded logging

---

clustering/infinispan/WFLY-9664_Scattered_Cache.adoc

https://issues.jboss.org/browse/EAP7-867
https://issues.jboss.org/browse/WFLY-9664

WFLY-9664 Add support for configuring scattered caches

---

elytron/WFCORE-3596-named-permission-sets.adoc

https://issues.jboss.org/browse/WFCORE-3596

[WFCORE-3596] Introduce named permission sets in the Elytron subsystem configuration

---

webservices/WFLY-10203_EAP-887_JBossWS-JDK9.adoc

https://issues.jboss.org/browse/EAP7-887
https://issues.jboss.org/browse/WFLY-10203
https://issues.jboss.org/browse/WFLY-9128

JBossWS JDK9

---

clustering/infinispan/WFLY-9294_Add_security_configuration_for_Infinispan_remote_cache_store.adoc

https://issues.jboss.org/browse/WFLY-9294
https://issues.jboss.org/browse/EAP7-942

WFLY-9294 Add security configuration for Infinispan remote cache store

---

clustering/infinispan/EAP7-961_HotRod_client_injection_via_Resource_JNDI_injection.adoc

https://issues.jboss.org/browse/EAP7-961
https://issues.jboss.org/browse/WFLY-9860

EAP7-961 HotRod client injection via @Resource JNDI injection

---

clustering/api/WFLY-9842_CommandDispatcher_Enhancements.adoc

https://issues.jboss.org/browse/WFLY-9842
https://issues.jboss.org/browse/EAP7-989

WFLY-9842 Enhance CommandDispatcher async methods to use CompletableFutures

---

transactions/WFLY-9818-ws-at-async-integration-with-.net.adoc

https://issues.jboss.org/browse/WFLY-9818

[WFLY-9818] XTS integration for Narayana providing WS-AT Integration with .NET

---

jaxrs/WFLY-10500_EAP7-1003_JAX-RS_parameter_annotations_with_default_names.adoc

https://issues.jboss.org/browse/WFLY-10500
https://issues.jboss.org/browse/EAP7-1003

EAP7-1003 / WFLY-10500 JAX-RS parameter annotations with default names

---

jaxrs/WFLY-10503_EAP7-1009_SPI_to_modify_resource_metadata.adoc

https://issues.jboss.org/browse/WFLY-10503
https://issues.jboss.org/browse/EAP7-1009

WFLY-10503 / EAP7-1009 RESTEasy SPI to modify resource metadata

---

jaxrs/WFLY-10636_EAP7-1010.adoc

https://issues.jboss.org/browse/EAP7-1010
https://issues.jboss.org/browse/WFLY-10636

EAP7-1010 / WFLY-10636 RESTEasy extended async / reactive support

---

jaxrs/WFLY-10646_EAP7-1034_multivalue_param.adoc

https://issues.jboss.org/browse/WFLY-10646
https://issues.jboss.org/browse/EAP7-1034

WFLY-10646 / EAP7-1034 Multivalue @*Param

---

jaxrs/WFLY-10361_EAP7-997_AsychClientHttpEngine.adoc

https://issues.jboss.org/browse/WFLY-10361
https://issues.jboss.org/browse/EAP7-997

[WFLY-10361][EAP7-997] RESTEasy AsynchClientHttpEngine

---

cli/EAP7-979_Allow_CLI_output_scrolling.adoc

WFCORE: https://issues.jboss.org/browse/WFCORE-3568
EAP7: https://issues.jboss.org/browse/EAP7-979

EAP7-979 WFCORE-3568 Allow CLI output scrolling

---

mod_cluster/WFLY-6803_Add_multi-server_support_to_mod_cluster.adoc

https://issues.jboss.org/browse/WFLY-6803
https://issues.jboss.org/browse/EAP7-977

WFLY-6803 Add multi-server support to mod_cluster

---

transaction/WFLY-10009_EAP7-981_Introduce_Maximum_Timeout.adoc

https://issues.jboss.org/browse/WFLY-10009
https://issues.jboss.org/browse/EAP7-981

WFLY-10009 Introduce a maximum-timeout management model attribute

---

elytron/WFCORE-3666-alternative-rolemapping.adoc

https://issues.jboss.org/browse/WFCORE-3666
https://issues.jboss.org/browse/EAP7-1008

[WFCORE-3666] Provide Elytron alternative to RoleMappingLoginModule

---

elytron/WFCORE-3819-custom-security-event-listener.adoc

https://issues.jboss.org/browse/WFCORE-3819
https://issues.jboss.org/browse/EAP7-1007

[WFCORE-3819] Add Elytron component to use a custom security event listener

---

elytron/WFCORE-3877-configurable-without-interface.adoc

https://issues.jboss.org/browse/WFCORE-3877
https://issues.jboss.org/browse/EAP7-1005

[WFCORE-3877] Make implementing Configurable interface optional for configurable components

---

console/EAP7-1033_Implement_new_Infinispan_resources.adoc

https://issues.jboss.org/browse/EAP7-1033

EAP7-1033: Implement new infinispan resources

---

migration/EAP7-990_JBoss_EAP_7.2_Server_Migration_Tool.adoc

EAP7: https://issues.jboss.org/browse/EAP7-990

EAP7-990: JBoss EAP 7.2 Server Migration Tool

---

server/EAP7-1075_read-provisioning-config.adoc

https://issues.jboss.org/browse/EAP7-1075
https://issues.jboss.org/browse/WFCORE-3991

EAP7-1075 read-provisioning-config management operation

---

microprofile/WFLY-10522_microprofile-config-smallrye_extension.adoc

Proposal to support Eclipse MicroProfile Config for applications
deployed in WildFly.
JIRA: https://issues.jboss.org/browse/WFLY-10522

[WFLY-10522] Support Eclipse MicroProfile Config

---

elytron/WFCORE-3970-reload-trust-manager.adoc

Jira: https://issues.jboss.org/browse/WFCORE-3970

[WFCORE-3970] Add Support for Elytron's trust-manager to be dynamically reloaded

---

controller/WFCORE-433_git-persistence.adoc

Jira: https://issues.jboss.org/browse/WFCORE-433
JBEAP: https://issues.jboss.org/browse/EAP7-728
PR: https://github.com/wildfly/wildfly-core/pull/3352

[WFCORE-433]: Using Git for persisting configuration files

---

logging/WFCORE-2953-socket-handler.adoc

https://issues.jboss.org/browse/WFCORE-2953
FYI @nziakova

[WFCORE-2953] Add socket-handler proposal for the logging subsystem.

---

console/EAP7-766_Unify_Wording_For_Deployment_Operations.adoc

https://issues.jboss.org/browse/EAP7-766

EAP7-766: Analysis document for EAP7-766

---

console/EAP7-1030_Add_support_for_undertow_session_operations.adoc

https://issues.jboss.org/browse/EAP7-1030

EAP7-1030: Add support for undertow session operations

---

console/EAP7-752_Support_kill_and_destroy_operations_for_server_groups.adoc

https://issues.jboss.org/browse/EAP7-752

EAP7-752: Support kill and destroy operations for server-groups

---

console/EAP7-749_Expose_EJB_runtime_data.adoc

https://issues.jboss.org/browse/EAP7-749

EAP7-749: Expose EJB runtime data / statistics

---

console/EAP7-750_Expose IO_worker_runtime_data.adoc

https://issues.jboss.org/browse/EAP7-750

EAP7-750: Expose IO worker runtime data / statistics

---

jaxrs/WFLY-10646_EAP7-1034_multivalue_param.adoc

Follow-up from comments at https://github.com/wildfly/wildfly-proposals/pull/99

[WFLY-10646][EAP7-1034] dev doc improvements

---

microprofile/WFLY-10709-MicroProfile-Tracing-Extension.adoc

As a follow up from #106, this adds a clarification about Jaeger components.
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

[WFLY-10709] Added clarification about the Jaeger components

---

agroal/WFLY-10328_EAP7-983_Agroal-subsytem.adoc

EAP feature https://issues.jboss.org/browse/EAP7-983

WFLY-10328 Agroal subsystem

---

undertow/WFLY-10084_Proxy_Protocol.adoc

https://issues.jboss.org/browse/WFLY-10084

[WFLY-10084] Proxy Protocol - dev and qe contacts fix

---

messaging/WFLY-10518_artemis_no_local_broker.adoc

JIRA: https://issues.jboss.org/browse/WFLY-10518

[WFLY-10518] Connections to remote Artemis broker

---

elytron/WFCORE-3966-jwt-realm-jku.adoc

https://issues.jboss.org/browse/EAP7-1068
https://issues.jboss.org/browse/WFCORE-3966
https://issues.jboss.org/browse/ELY-1551

[WFCORE-3966] JwtValidator jku and kid header parameters

---

cli/EAP7-1113_Disable_CLI_paging_with_an_option.adoc

Issue: https://issues.jboss.org/browse/EAP7-1113

[EAP7-1113] [WFCORE-4127] Disable CLI paging with an option

---

elytron/WFCORE-4144-default-ssl_context-server.adoc

https://issues.jboss.org/browse/WFCORE-4144

[WFCORE-4144] Add support for registering a default SSLContext within the server.

---

messaging/WFLY-10326_messaging_global_resource_usage.adoc

Dev analysis for https://issues.jboss.org/browse/WFLY-10326

[WFLY-10326] Add Setting to Control Global Resources Usage for Messaging Servers

---

console/EAP7-664_Provide_UI_For_Security_Managewr.adoc

https://issues.jboss.org/browse/EAP7-664

EAP7-664: Provide UI for security manager

---

console/EAP7-1112_Guided_Tour.adoc

https://issues.jboss.org/browse/EAP7-1112

EAP7-1112: Guided Tour

---

security/WFCORE-3873_SNI_Support.adoc

https://issues.jboss.org/browse/EAP7-726
https://issues.jboss.org/browse/WFCORE-3873

[WFCORE-3873] Update doc to reflect reality

---

clustering/ejb/WFLY-11597_Eager_passivation.adoc

https://issues.jboss.org/browse/WFLY-11597

WFLY-11597 Eager passivation of SFSBs.

---

server/WFCORE-4251_list_modules_in_deployment_classpath.adoc

EAP issue: https://issues.jboss.org/browse/EAP7-521
Upstream issue: https://issues.jboss.org/browse/WFCORE-4251

[WFCORE-4251] List modules on deployments classpath via a Management Operation

---

core/WFCORE-1427_Suspend_Resume_servers_by_host_controller.adoc

Jira issues:
https://issues.jboss.org/browse/EAP7-601
https://issues.jboss.org/browse/WFCORE-3724
https://issues.jboss.org/browse/WFCORE-1427

[WFCORE-1427] Provide ability to suspend and resume the set of servers managed by a specific host controller

---

console/EAP7-1156_Display_open_network_ports_for_a_managed_server.adoc

https://issues.jboss.org/browse/EAP7-1156

EAP7-1156 Display open network ports for a managed server

---

console/EAP7-762_Support_socket_log_handler.adoc

https://issues.jboss.org/browse/EAP7-762

EAP7-762 Support socket log handler (HAL)

---

console/EAP7-1131_Show_logs_from_logging-profile_in_log_viewer.adoc

https://issues.jboss.org/browse/EAP7-1131

EAP7-1131 Show logs from logging-profile in log viewer

---

console/EAP7-1157_Add_support_for_server-ssl-sni-context.adoc

https://issues.jboss.org/browse/EAP7-1157

EAP7-1157 - Add support for server-ssl-sni-context

---

console/EAP7-1130_Add_support_to_several_messaging-activemq_resources.adoc

https://issues.jboss.org/browse/EAP7-1130

EAP7-1130 Add support to several messaging-activemq resources

---

console/EAP7-1060_Make_expose_EAP_metrics_configurable.adoc

https://issues.jboss.org/browse/EAP7-1060

EAP7-1060: Make 'Expose EAP Metrics' configurable

---

console/EAP7-1062_Display_microprofile_health_checks_on_HAL.adoc

https://issues.jboss.org/browse/EAP7-1062

EAP7-1062 Display microprofile health checks on HAL

---

console/HAL-1545_Enhance_the_SSL_Wizard_to_add_support_to_LetsEncrypt_CA.adoc

https://issues.jboss.org/browse/HAL-1545

HAL-1545 Enhance the SSL Wizard to add support to LetsEncrypt CA

---

console/EAP7-1159_Support_runtime_operations_for_messaging_servers.adoc

https://issues.jboss.org/browse/EAP7-1159

EAP7-1159: Support runtime operations for messaging servers

---

console/EAP7-1163_Show_active_management_operation.adoc

https://issues.jboss.org/browse/EAP7-1163

EAP7-1163 Show active management operation from hosts and servers in a central place

---

console/EAP7-1133_Add_init_runtime_operation_to_trust-manager.adoc

https://issues.jboss.org/browse/EAP7-1133

EAP7-1133 Add "init" runtime operation to trust-manager

---

console/EAP7-773_Multi-server_support_for_mod_cluster.adoc

https://issues.jboss.org/browse/EAP7-773

EAP7-773 Multi-server support for mod_cluster

---

console/EAP7-1132_Replace_list-log-files.adoc

https://issues.jboss.org/browse/EAP7-1132

EAP7-1132 Replace 'list-log-files' with using the 'log-file' resource

---

console/EAP7-1134_Update_Modcluster_view.adoc

https://issues.jboss.org/browse/EAP7-1134

EAP7-1134 Update Modcluster view for new resources load-provider

---

console/EAP7-1164_Show_notification_of_non_progressing_operations.adoc

https://issues.jboss.org/browse/EAP7-1164

EAP7-1164 Show notification of non progressing operations

---

ejb/WFLY-11622_Multiple_delivery_group_for_MDBs.adoc

Jira: https://issues.jboss.org/browse/WFLY-11622

[WFLY-11622] Multiple delivery group support for Message Driven Beans

---

clustering/singleton/WFLY-10832_Singleton_Service_Metrics.adoc

https://issues.jboss.org/browse/WFLY-10832

WFLY-10832 Determine the primary provider of Singleton Service using CLI

---

clustering/web/WFLY-5550_Distributable_Web_Subsystem.adoc

https://issues.jboss.org/browse/WFLY-5550

WFLY-5550 Distributable Web subsystem

---

clustering/web/WFLY-5497_Distributable_Shared_Session_Config.adoc

https://issues.jboss.org/browse/WFLY-5497

WFLY-5497 Add <distributable/> to shared-session-config schema

---

clustering/singleton/WFLY-11098_Singleton_Service_Election_Listener.adoc

https://issues.jboss.org/browse/WFLY-11098

WFLY-11098 Singleton service election listeners

---

elytron/WFLY-7186-security-api-integration.adoc

https://issues.jboss.org/browse/WFLY-7186
https://issues.jboss.org/browse/EAP7-993

[WFLY-7186] Add analysis for supporting the Security API defined under JSR-375 with WildFly Elytron.

---

logging/WFCORE-4355-event-logger.adoc

https://issues.jboss.org/browse/WFCORE-4355

[WFCORE-4355] Add proposal for event-logging API.

---

messaging/WFLY-11404_configurable_journal_file_open_timeout.adoc

Jira: https://issues.jboss.org/browse/WFLY-11404

WFLY-11404 Add journal-file-open-timeout attribute to messaging server

---

undertow/WFLY-11031_Formatted_Access_Logs.adoc

https://issues.jboss.org/browse/WFLY-11031

[WFLY-11031] Add proposal for JSON access logging.

---

clustering/web/WFLY-7719_HotRod-based_distributed_session_manager.adoc

https://issues.jboss.org/browse/WFLY-7719

WFLY-7719 HotRod-based distributed session manager

---

messaging/WFLY-12038_enable1prefixes.adoc

Jira: https://issues.jboss.org/browse/WFLY-12038

[WFLY-12038] Expose the enable1Prefixes configuration on external (pooled) connection factories.

---

console/HAL-1578_Customise_Browser_Title.adoc

https://issues.jboss.org/browse/HAL-1578

HAL-1578: Customise Browser Title

---

elytron/WFCORE-3947-ocsp-ssl-revocation.adoc

https://issues.jboss.org/browse/WFCORE-3947
https://issues.jboss.org/browse/EAP7-715

[WFCORE-3947] Support SSL Certificate revocation using OCSP

---

elytron/WFCORE-4361-evidence-decoder.adoc

https://issues.jboss.org/browse/WFCORE-4361

[WFCORE-4361] Enhanced mapping of an X509Certificate to the underlying identity

---

microprofile/WFLY-12189_microprofile-config-tck.asciidoc

JIRA: https://issues.jboss.org/browse/WFLY-12189

[WFLY-12189] Add MicroProfile Config TCK to the WildFly integration test suite

---

elytron/ELY-1686-legacy-properties-files-into-FileSystemRealm-utility.adoc

Jira: https://issues.jboss.org/browse/ELY-1686

[ELY-1686] Utility to port legacy properties file into a FileSystemRealm

---

clustering/web/WFLY-6944_Ranked_routing.adoc

https://issues.jboss.org/browse/WFLY-6944

WFLY-6944 Ranked routing

---

clustering/web/WFLY-6944_Ranked_routing.adoc

Updates for https://issues.jboss.org/browse/WFLY-12144

WFLY-12144 Add support for configuring load-balancer with ranked routing

---

messaging/WFLY-5286_add_runtime_journal_type_attribute.adoc

* Expose the effectively used journal type
Jira: https://issues.jboss.org/browse/WFLY-5286

[WFLY-5286]: Provide CLI operation which returns used journal type -NIOxASYNCIO.

---

messaging/WFLY-6684_jms_bridge_statistics.adoc

* Adding RFE description.
Jira: https://issues.jboss.org/browse/WFLY-6684

[WFLY-6684]: JMS Bridge should display statistics about messages that have been processed.

---

messaging/WFLY-12243_monitor_artemis_resource_adapter_thread_pools.adoc

* Expose metrics on global client thread pool and scheduled thread pool.
Jira: https://issues.jboss.org/browse/WFLY-12243

[WFLY-12243]: Monitor resource adapter thread pools.

---

microprofile/WFLY-12306_Updating_opentracing_to_1.3.adoc

Jira: https://issues.jboss.org/browse/WFLY-12306

[WFLY-12306]: Transition  OpenTracing to 1.3

---

microprofile/WFLY-12228_upgrade_microprofile-health_2.0.1.adoc

JIRA: https://issues.jboss.org/browse/WFLY-12228

[WFLY-12228] Upgrade MicroProfile Health 2.0.1

---

elytron/ELY-1712-enhanced-audit-logging.adoc

Jira: https://issues.jboss.org/browse/EAP7-699

[WFCORE-4394] Enhanced audit logging

---

elytron/WFCORE-4496-principal-transformer-in-aggregate-realm.adoc

https://issues.jboss.org/browse/EAP7-1220
https://issues.jboss.org/browse/WFCORE-4496 
https://issues.jboss.org/browse/WFLY-12202
https://issues.jboss.org/browse/ELY-1829

[WFCORE- 4496] - Adding principal-transformer in aggregate-realm

---

logging/WFCORE-4336-custom-filters.adoc

https://issues.jboss.org/browse/WFCORE-4336

[WFCORE-4336] Add analysis document for adding custom filters.

---

clustering/infinispan/WFLY-12165_Remote_Cache_Metrics.adoc

https://issues.jboss.org/browse/WFLY-12165

WFLY-12165 Expose management metrics for HotRod caches

---

undertow/WFLY-11764_Preserve_Path_on_Forward.adoc

WFLY Jira: https://issues.jboss.org/browse/WFLY-11764
EAP7 Jira: https://issues.jboss.org/browse/EAP7-1341

[WFLY-11764] Analysis for WFLY-11764

---

console/HAL-1601_Expose_named-formatter_attribute_on_syslog-handler_resource.adoc

https://issues.jboss.org/browse/HAL-1601

HAL-1601: Expose new named-formatter attribute on the syslog-handler resource

---

console/HAL-1607_Configure_HotRod_distributable-web_subsystem.adoc

https://issues.jboss.org/browse/HAL-1607

HAL-1607: Configure HotRod session manager in distributable-web subsystem

---

console/HAL-1609_Enhanced_password_mappers.adoc

https://issues.jboss.org/browse/HAL-1609

HAL-1609: Configure new / enhanced password mappers

---

microprofile/WFLY-12686_upgrade_microprofile_metrics_2.2.0.adoc

JIRA: https://issues.jboss.org/browse/WFLY-12686

[WFLY-12686] Upgrade MicroProfile Metrics 2.2.1

---

microprofile/WFLY-12590_Integrate_MicroProfile_Fault_Tolerance_2.0.adoc

Jira
https://issues.jboss.org/browse/WFLY-12590
https://issues.jboss.org/browse/EAP7-1347

Proposal for WFLY-12590 Integrate MicroProfile Fault Tolerance 2.0

---

concurrency/WFLY-11255_EE_Concurrency_Utilities_Managed_Executors_Runtime_Stats.adoc

Issue: https://issues.jboss.org/browse/WFLY-11255

[WFLY-11255] Managed Executor Runtime Stats

---

microprofile/WFLY-12758_integrate_opentracing.adoc

Describing the management API changes that will be implemented in the
'microprofile-opentracing-smallrye' subsystem to cover the configuration
of tracers and their injections.
Jira: https://issues.jboss.org/browse/WFLY-12758

[WFLY-12758]: Integrate opentracing

---

jaxrs/WFLY-12298_Change_RESTEASY_settings.adoc

[WFLY-12298] Remove references to CLI.
[WFLY-12298] 1) Add more details about scope of changes, and 2) update
QA assignment.
[WFLY-12298] Reorganize, add "Requirements", "Nono Requirements"
sections.
[WFLY-12298] Change to "Non Requirements" section.
[WFLY-12298] Elaborated on choice of implemented parameters.

[WFLY-12298] Allow configuring RESTEasy through CLI

---

ee/WFCORE_2147_Wildfly_core_descriptor_based_property_replacement.adoc

EAP issue: https://issues.jboss.org/browse/EAP7-1162
Upstream issue: https://issues.jboss.org/browse/WFCORE-2147

[WFCORE-2147] Enable descriptor based property replacement for files parsed by wildfly-core

---

wf-galleon/WFLY-11989_Galleon_Maven_Repository.adoc

Issue: https://issues.jboss.org/browse/WFGP-132

Proposal for WFLY-11989 offliner file with everything needed allowing to provision server using Galleon

---

elytron/WFCORE-4172-tls-1.3.adoc

https://issues.jboss.org/browse/WFCORE-4172

[WFCORE-4172] Add support for TLS 1.3

---

microprofile/WFLY-12313_MicroProfile_OpenAPI_1.1.adoc

https://issues.jboss.org/browse/WFLY-12313

WFLY-12313 Integrate MicroProfile OpenAPI 1.1

---

cloud/WFLY-11824_wildfly_operator_kubernetes.adoc

JIRA: https://issues.jboss.org/browse/WFLY-11824

[WFLY-11824] WildFly Operator for Kubernetes/OpenShift

---

microprofile/WFLY-12685_upgrade_microprofile_health_2.1.0.adoc

JIRA: https://issues.jboss.org/browse/WFLY-12685

[WFLY-12685] Upgrade MicroProfile Health 2.1.0

---

microprofile/WFLY-13024_Integrate_MP_Fault_Tolerance_2_1.adoc

https://issues.redhat.com/browse/WFLY-13024
https://issues.redhat.com/browse/EAP7-1428

WFLY-13024 Integrate MP Fault Tolerance 2.1

---

microprofile/WFLY-13022_upgrade_microprofile-metrics_2.3.adoc

JIRA: https://issues.redhat.com/browse/WFLY-13022

[WFLY-13022] Upgrade MicroProfile Metrics 2.3

---

elytron/WFLY-11697_WS_client_integration_with_Elytron.adoc

JIRA: 
https://issues.jboss.org/browse/WFLY-11697

[WFLY-11697] WS integration with Elytron on the client side

---

management/WFCORE-1110_Custom_HTTP_Management_Headers.adoc

https://issues.jboss.org/browse/WFCORE-1110

[WFCORE-1110] Add support for custom headers to the HTTP management endpoints.

---

microprofile/WFLY-12313_MicroProfile_OpenAPI_1.1.adoc
microprofile/WFLY-13207_MicroProfile_OpenAPI_quickstart.adoc

https://issues.redhat.com/browse/WFLY-13207

WFLY-13207 Quickstart for MP OpenAPI 1.1.2

---

microprofile/WFLY-12770_Create_quickstart_for_MicroProfile_Fault_Tolerance.adoc

https://issues.redhat.com/browse/WFLY-12770
https://issues.redhat.com/browse/EAP7-1370
Implementation PR: https://github.com/wildfly/quickstart/pull/382

WFLY-12770 Create quickstart for MicroProfile Fault Tolerance 2.1

---

elytron/WFCORE-3947-ocsp.adoc

https://issues.jboss.org/browse/WFCORE-3947
https://issues.jboss.org/browse/EAP7-715

[WFCORE-3947] OCSP trustmanager

---

elytron/WFCORE-4058-automatic-keystore-detection.adoc

https://issues.jboss.org/browse/EAP7-675[EAP7-675]
https://issues.jboss.org/browse/ELY-1650[ELY-1650]
https://issues.jboss.org/browse/WFCORE-4058[WFCORE-4058]

[WFCORE-4058] Automatic detection of file based KeyStore types.

---

migration/EAP7-1153_JBoss_EAP_7.3_Server_Migration_Tool.adoc

EAP7: https://issues.jboss.org/browse/EAP7-1153

EAP7-1153: JBoss EAP 7.3 Server Migration Tool

---

microprofile/WFLY-12737_quickstart-for-mp-health-2.2.adoc

https://issues.jboss.org/browse/WFLY-12737

[WFLY-12737] Quickstart for MP Health 2.2

---

microprofile/WFLY-12802_EAP7-1374_quickstart-for-mp-config-1.3.adoc

https://issues.jboss.org/browse/WFLY-12802

[WFLY-12802] Quickstart for MP Config 1.4

---

microprofile/WFLY-12809_EAP7-1373_quickstart-for-mp-metrics-2.2.adoc

https://issues.jboss.org/browse/WFLY-12809

[WFLY-12809] Quickstart for MP Metrics 2.3

---

microprofile/WFLY-12829_EAP7-1369_quickstart-for-mp-opentracing-1.3.adoc

https://issues.jboss.org/browse/WFLY-12829

[WFLY-12829] Quickstart for MP OpenTracing 1.3

---

undertow/WFLY-13003_Support_SameSite_Cookie_Attribute.adoc

Jira: https://issues.redhat.com/browse/WFLY-13003
EAP7: https://issues.redhat.com/browse/EAP7-1422

[WFLY-13003] Analysis document for SameSite cookie attribute changes

---

console/HAL-1608_Configure_enable-amq1-prefix.adoc

https://issues.jboss.org/browse/HAL-1608

HAL-1608: Configure enable-amq1-prefix attribute

---

elytron/WFCORE-4150-credential-store-automatic-updates.adoc

https://issues.jboss.org/browse/WFCORE-4150

[WFCORE-4150] Support automatically adding and updating credentials in a credential store

---

elytron/WFCORE-4750-regex-role-mapper.adoc

Proposal for https://issues.jboss.org/browse/WFCORE-4750

[WFCORE-4750] Introduce regex mapper for security roles in Elytron

---

elytron/WFCORE-4725-runtime-attributes.adoc

https://issues.jboss.org/browse/WFCORE-4725

[WFCORE-4725] Making additional attributes available for authorization decisions

---

elytron/WFCORE-4486-multiple-security-realms-failover.adoc

https://issues.jboss.org/browse/WFCORE-4486

[WFCORE-4486] Support for multiple security realms - Failover

---

console/WFLY-13490-Galleon_layer_web_console.adoc

Jira issue: https://issues.redhat.com/browse/WFLY-13490

[WFLY-13490] Add Galleon layer for the web management console

---

ejb/WFLY-13354-galleon-for-ejb.adoc

JIRA: https://issues.redhat.com/browse/WFLY-13354

Proposal for WFLY-13354 Add Galleon layers for the EJB subsystem

---

microprofile/WFLY-12681_Provide_a_microprofile-platform_Galleon_layer.adoc

https://issues.redhat.com/browse/WFLY-12681
https://issues.redhat.com/browse/EAP7-1396

WFLY-12681 Provide a 'microprofile-platform' Galleon layer

---

batch/WFLY-13128_Galleon_layer_batch.adoc

Jira issue: https://issues.redhat.com/browse/WFLY-13128
PR: https://github.com/wildfly/wildfly/pull/13016

[WFLY-13128] Galleon layer for Batch subsystem

---

sar/WFLY-13352-Add_galleon_layer_sar_subsystem.adoc

Jira issue: https://issues.redhat.com/browse/WFLY-13352

[WFLY-13352] Add Galleon layer for SAR subsystem

---

mail/WFLY-13351_galleon_layer_for_mail_subsystem.adoc

Jira issue: https://issues.redhat.com/browse/WFLY-13351

[WFLY-13351] Galleon layer for the Mail subsystem

---

jaxrs/WFLY-13585_Galleon_layer_jsonp_support.adoc

Jira issue: https://issues.redhat.com/browse/WFLY-13585

[WFLY-13585] Add Galleon layer for JSON-P

---

jaxrs/WFLY-13586_Galleon_layer_jsonb.adoc

Jira issue: https://issues.redhat.com/browse/WFLY-13586

[WFLY-13586] Add a Galleon layer for JSON Binding support

---

pojo/WFLY-13353_galleon_layer_for_pojo_subsystem.adoc

Jira issue: https://issues.redhat.com/browse/WFLY-13353

[WFLY-13353] Galleon layer for the Pojo subsystem

---

elytron/WFLY-11868_RESTEasy_client_integration_with_Elytron.adoc

JIRA: https://issues.jboss.org/browse/WFLY-11868

[WFLY-11868] RESTEasy integration with Elytron on the client side

---

elytron/ELY-1921-http-external-mechanism.adoc

https://issues.redhat.com/browse/ELY-1921
https://issues.redhat.com/browse/EAP7-1323

[ELY-1921] HTTP External Security Not Supported by Elytron

---

jsf/WFLY-13350_galleon_layer_for_jsf_support.adoc

Jira issue: https://issues.jboss.org/browse/WFLY-13350

[WFLY-13350] Galleon layer for Jakarta Server Faces support

---

elytron/WFCORE-5095-automatic-self-signed-certificate-generation.adoc

https://issues.redhat.com/browse/WFCORE-5095

[WFCORE-5095] Add the ability to make use of an automatically generated self-signed certificate with Elytron

---

messaging/WFLY-9213_Implement_the_Pause_method_for_a_Topic.adoc

Jira: https://issues.jboss.org/browse/WFLY-9213

[WFLY-9213]: Implement the Pause method for a Topic via Management APIs

---

messaging/WFLY-12825_Artemis_network_health_check_feature.adoc

Jira: https://issues.jboss.org/browse/WFLY-12825

[WFLY-12825]: Artemis network health check feature not configurable from WildFly

---

messaging/WFLY-13959_critical_analyzer.adoc

[WFLY-13959]: Add critical-analyzer configuration to WildFly Management

---

microprofile/WFLY-14277_MicroProfile_JWT_1_2_Upgrade.adoc

https://issues.redhat.com/browse/WFLY-14277

[WFLY-14277] Add analysis to upgrade to support MicroProfile JWT 1.2.

---

microprofile/WFLY-14245_MicroProfile_OpenAPI_2.0.adoc

https://issues.redhat.com/browse/WFLY-14245

WFLY-14245 Integrate MicroProfile OpenAPI 2.0

---

microprofile/WFLY-14201_upgrade_microprofile-config_2.0.adoc

https://issues.redhat.com/browse/WFLY-14201

[WFLY-14201] MP Config 2.0 proposal

---

microprofile/WFLY-14261_upgrade-microprofile-health-3.0.adoc

https://issues.redhat.com/browse/WFLY-14261

[WFLY-14261] MP Health 3.0 proposal

---

microprofile/WFLY-14281_Integrate-MP-Fault-Tolerance-3.0.adoc

Replaces
https://github.com/wildfly/wildfly-proposals/pull/361
Jira
https://issues.redhat.com/browse/EAP7-1594

EAP7-1594 Integrate MP Fault Tolerance 3.0 into EAP

---

messaging/WFLY-13991_keep_corrupted_journal_files.adoc

Issue: https://issues.redhat.com/browse/WFLY-13991

[WFLY-13991]: Keep corrupted journal files in Artemis.

---

microprofile/WFLY-13640_MicroProfile_Reactive_Messaging.adoc

Proposal for inclusion of Reactive Messaging (which in turn needs Reactive Streams Operators and Context Propagation)
https://issues.redhat.com/browse/WFLY-13640

[WFLY-13640] MP Reactive Messaging with Focus on Apache Kafka

---

undertow/WFLY-12473_obfuscate-session-route.adoc

WFLY Jira: https://issues.jboss.org/browse/WFLY-12473
EAP7 Jira: https://issues.jboss.org/browse/EAP7-1187
WildFly PR: https://github.com/wildfly/wildfly/pull/12883

[WFLY-12473] Allow instance-id obfuscation in Undertow session route

---

elytron/WFLY-14074-normalization-of-principal-propagation.adoc

https://issues.redhat.com/browse/WFLY-14074

[WFLY-14074] Proposal for Normalization of principal propagation/injection across elytron and legacy

---

messaging/WFLY-14133_configurable_bridge_call_timeout.adoc

https://issues.redhat.com/browse/WFLY-14133
https://issues.redhat.com/browse/EAP7-1622

WFLY-14133 Make call-timeout configurable on the core bridge

---

microprofile/WFLY-14391-MicroProfile_Reactive_Messaging_1.0_With_Kafka_Quickstart.adoc

https://issues.redhat.com/browse/WFLY-14391

[WFLY-14391] Reactive Messaging 1.0 with Kafka QuickStart

---

clustering/infinispan/WFLY-14468_Add_support_for_using_Infinispan_APIs_from_a_deployment.adoc

https://issues.redhat.com/browse/WFLY-14468
https://issues.redhat.com/browse/EAP7-1445

WFLY-14468 Add support for using Infinispan APIs from a deployment

---

microprofile/WFLY-14580_upgrade_microprofile_rso_2.0.adoc

https://issues.redhat.com/browse/WFLY-14580

[WFLY-14580] Reactive Streams Operators 2.0

---

elytron/WFCORE-5170-multiple-certificate-revocation-lists.adoc

https://issues.redhat.com/browse/WFCORE-5170

[WFCORE-5170] Certificate Revocation Lists Proposal

---

cloud/WFLY-14479_helm_charts.adoc

As an user, I want to build and deploy WildFly applications on OpenShift using Helm Chart
JIRA: https://issues.redhat.com/browse/WFLY-14479

[WFLY-14479] Helm Chart for WildFly

---

microprofile/WFLY-14940_upgrade-microprofile-health-3.1.adoc

https://issues.redhat.com/browse/WFLY-14940

[WFLY-14940] Provide support for MicroProfile Health 3.1

---

microprofile/WFLY-14148-microprofile-opentracing-move.adoc

Jira: https://issues.redhat.com/browse/WFLY-14148

[WFLY-14148]: WFLY-14148 Remove MicroProfile Opentracing from WildFlyEE

---

messaging/WFLY-13797_galleon_layer_for_remote_artemis.adoc

[WFLY-13797] Galleon layer for remote ActiveMQ Artemis broker integration support

---

microprofile/WFLY-14932_mp_reactive_messaging_kafka_api.adoc

https://issues.redhat.com/browse/WFLY-14932

[WFLY-14932] MicroProfile Reactive Messaging Kafka user API

---

elytron/WFCORE-5178_native-support-for-oidc.adoc

This proposal is an initial draft. More updates will be added based on discussions or any issues found during the implementation.
https://issues.redhat.com/browse/WFCORE-5178

[WFCORE-5178] Native support for OIDC

---

microprofile/WFLY-14800-MicroProfile_Reactive_Messaging_QuickStart_Update_For_2.0.adoc

https://issues.redhat.com/browse/WFLY-14800

[WFLY-14800] Modernise quickstart for Reactive Messaging 2.0

---

elytron/WFCORE-5483-custom-loginmodule-compatible-sec-realm.adoc

https://issues.redhat.com/browse/WFCORE-5483

[WFCORE-5483] "Provide a LoginModule compatible security realm" proposal

---

console/HAL-1710_update_passwords_in_credential_store.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1710

HAL-1710: Analysis document

---

console/HAL-1737_Display_content_hash.adoc

https://issues.redhat.com/browse/HAL-1737

HAL-1737: Analysis document

---

console/HAL-1625_Support_pause_for_JMS_topics.adoc
console/HAL-1626_Support_pause_for_JMS_topics.adoc

https://issues.redhat.com/browse/HAL-1625

HAL-1625: Support pause for JMS topics

---

console/HAL-1597_Configure_session_affinity.adoc

https://issues.redhat.com/browse/HAL-1597

HAL-1597: Configure session affinity using multiple routes if supported by balancer

---

console/HAL-1645_Support_adding_HTTP_headers_to_management_console_responses.adoc

https://issues.redhat.com/browse/HAL-1645

HAL-1645: Analysis document

---

console/HAL-1729_Show_non-heap-memory-usage.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1729

HAL-1729: Add analysis document

---

console/HAL-1580_Global_EJB_Server_Side_Interceptors_Configuration.adoc

https://issues.redhat.com/browse/HAL-1580

HAL-1580: Configure Global EJB Server Side Interceptors

---

batch/WFLY-15525_Limit_number_of_records_loaded_by_jdbc_store.adoc

https://issues.redhat.com/browse/WFLY-15525
https://issues.redhat.com/browse/EAP7-1821

WFLY-15525 Limit number of records loaded by the JDBC job repository

---

jca/WFLY-14347_Allow_to_configure_module_for_custom_validation_classes.adoc

https://issues.redhat.com/browse/WFLY-14347
https://issues.redhat.com/browse/EAP7-1189

[WFLY-14347] Allow to configure module for custom validation classes

---

elytron/ELY-2078-encryption-for-FilesystemSecurityRealm.adoc

https://issues.redhat.com/browse/ELY-2078
https://issues.redhat.com/browse/WFCORE-5530
https://issues.redhat.com/browse/WFLY-15075

[ELY-2078] Add encryption support to FilesystemSecurityRealm

---

core/WFCORE-4314_enchance_keystore_commands_alias.adoc

https://issues.jboss.org/browse/WFCORE-4314
https://issues.jboss.org/browse/EAP7-1266

[WFCORE-4314] enchance keystore commands alias

---

clustering/web/WFLY-13904_ProtoStream_support_for_distributed_web_applications.adoc

https://issues.redhat.com/browse/WFLY-13904

WFLY-13904 ProtoStream support for distributable web applications.

---

clustering/ejb/WFLY-7628_Distributed_EJB_Timers.adoc

https://issues.redhat.com/browse/WFLY-7628

WFLY-7628 Distributed EJB timers.

---

maven/WFMP-174_image_goal.adoc

As an user, I want to build and push an application image from the wildfly-maven-plugin
JIRA: https://issues.redhat.com/browse/WFMP-174

[WFMP-174] New image goal for the wildfly-maven-plugin

---

console/HAL-1604_Expose_journal-file-open-timeout_attribute.adoc

https://issues.jboss.org/browse/HAL-1604

HAL-1604: Make journal-file-open-timeout attribute configurable for messaging server resource

---

microprofile/WFLY-12823_quickstart-for-mp-rest-client-1.4.adoc

https://issues.jboss.org/browse/WFLY-12823

[WFLY-12823] Quickstart for MP REST-client 1.4

---

quickstarts/WFLY-13713_Bootable_jar_support_for_MicroProfile_Quickstarts.adoc

Issue: https://issues.redhat.com/browse/WFLY-13713

[WFLY-13713] Bootable jar support for MicroProfile Quickstarts

---

logging/WFCORE-5781-drop-log4j.adoc

https://issues.redhat.com/browse/WFCORE-5781
Signed-off-by: James R. Perkins <jperkins@redhat.com>

[WFCORE-5781] Remove log4j 1.x support

---

microprofile/WFLY-13208_Microprofile_BOM.adoc

Issue: https://issues.jboss.org/browse/WFLY-13208

[WFLY-13208] adds proposal for the Microprofile BOM

---

console/HAL-1603_Configure_messaging_clusters_behind_HTTP_load_balancers.adoc

https://issues.jboss.org/browse/HAL-1603

HAL-1603: Configure messaging clusters behind http load balancers

---

elytron/WFLY-15274-make-wildfly-able-to-use-last-openssl-3.adoc

https://issues.redhat.com/browse/WFLY-15274

[WFLY-15274] Make WildFly able to use latest OpenSSL 3.0.0 libraries

---

console/HAL-1758_Legacy_security_clean_up.adoc

https://issues.redhat.com/browse/HAL-1758

HAL-1758: Legacy security clean up

---

microprofile/WFLY-15006_reactive_messaging_with_rhosak.adoc

https://issues.redhat.com/browse/WFLY-15006

[WFLY-15006] Reactive Messaging integration with RHOSAK

---

clustering/jgroups/WFLY-8770_Integrate_NATIVE_S3_PING_discovery_protocol.adoc
clustering/jgroups/WFLY-8770_Integrate_aws_S3_PING_discovery_protocol.adoc

https://issues.redhat.com/browse/WFLY-8770
https://issues.redhat.com/browse/EAP7-863

WFLY-8770 Integrate aws.S3_PING discovery protocol

---

openshift/WFLY-14936_New_S2I_Image.adoc

Proposal for new WildFly s2i and runtime images.

Proposal for WFLY-14936, New WildFly S2I images

---

console/HAL-1780_Adjust_naming_master-slave_primary-secondary.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1780

HAL-1780: Adjust naming in console

---

quickstarts/EAP7-1891_EAP8_Beta_Quickstarts.adoc

Issue: [EAP7-1891](https://issues.redhat.com/browse/EAP7-1891)

[EAP7-1891] EAP8 Beta Quickstarts

---

quickstarts/WFLY-16140_Remove_outdated_Quickstarts.adoc

Issue: https://issues.redhat.com/browse/WFLY-16140

[WFLY-16140] Remove Outdated Quickstarts

---

console/HAL-1779_Replace_discovery-group_and_broadcast-group_resources.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1779

HAL-1779: Replace 'discovery-group' and 'broadcast-group' resources

---

messaging/WFLY-7232_support_elytron_sslcontext.adoc

Jira: https://issues.redhat.com/browse/WFLY-7232

[WFLY-7232]: Add support for Elytron provided SSLContexts in Artemis

---

clustering/web/WFLY-16043_Allow_configuration_of_an_arbitrary_cookie_to_use_for_web_request_affinity.adoc

Proposal for
https://issues.redhat.com/browse/WFLY-16043

WFLY-16043 Allow configuration of an arbitrary cookie to use for web request affinity

---

clustering/infinispan/WFLY-13520_Add_support_for_Infinispan_query_counters_locks_and_CDI.adoc

https://issues.redhat.com/browse/WFLY-13520
https://issues.redhat.com/browse/EAP7-1446

WFLY-13520 Add support for Infinispan query, counters, locks, and CDI

---

build/WFLY-17648_Jakarta_EE_Core_Profile.adoc

https://issues.redhat.com/browse/WFLY-17648
I'm not sure if the `build` directory is the right location, but it made the most sense for now.

[WFLY-17648] Add a new layer for the Jakarta EE 10 Core Profile.

---

jpa/EAP7-1986_Hibernate6_2.adoc
jpa/WFLY-17558_Hibernate6_2.adoc

WFLY-17558 for Hibernate ORM 6.2

---

messaging/WFLY-13798_Galleon_layer_embedded_broker.adoc

Jira: https://issues.redhat.com/browse/WFLY-13798
https://issues.redhat.com/browse/EAP7-1918

[WFLY-13798]: Add a Galleon layer for embedded broker messaging.

---

quickstarts/EAP7-1792_provide_quickstart_for_remote_connection_to_artemis_broker.adoc

Jira: https://issues.redhat.com/browse/EAP7-1792

[EAP7-1792]: Provide a quickstart with a remote connection to the broker.

---

openshift/CLOUD-3772_microprofile-platform_s2i.adoc

in S2i workflow
Issue: https://issues.jboss.org/browse/CLOUD-3772
EAP7 Plan: https://issues.jboss.org/browse/EAP7-1550

Proposal for CLOUD-3772, Support 'microprofile-platform' Galleon layer

---

backward-compatibility/WFLY-16296_JavaEE_And_JakartaEE_Compatibility.adoc

https://issues.redhat.com/browse/WFLY-16296
This PR supersedes https://github.com/wildfly/wildfly-proposals/pull/447#issuecomment-1467104759

[WFLY-16296] EAP6 and EAP7 applications have to communicate with EAP8 apps successfully

---

microprofile/WFLY-15405_microprofile_reactive_messaging_amqp.adoc

https://issues.redhat.com/browse/WFLY-15405

[WFLY-15405] MP Reactive Messaging AMQP connector proposal

---

microprofile/WFLY-17137-microprofile-jakarta-ee-10-mp6.1.adoc
microprofile/WFLY-17137-microprofile-jakarta-ee-10.adoc

https://issues.redhat.com/browse/WFLY-17137
#499 is the original proposal document, and targets MP Platform 6.0. This PR contains adjustments, in case we are in a position to support MP Platform 6.1.

[WFLY-17137] MicroProfile with Jakarta EE10 - MP 6.1 update

---

jaxp/WFLY-18846_JAXP_Specification_Version_1.6.adoc

https://issues.redhat.com/browse/WFLY-18846

[WFLY-18846] Support for JAXP Specification Version 1.6

---

design-doc-template.adoc

Update design-doc-templ with title prefix options

---

microprofile/WFLY-18383_EAP7-2105_quickstart-for-microprofile-lra.adoc

Quickstart for MicroProfile LRA

WFLY-18383 Quickstart for MicroProfile LRA

---

server/WFCORE-6728-reload-to-stability-level.adoc

https://issues.redhat.com/browse/WFCORE-6728

[WFCORE-6728] Ability to reload tests to a different stability level

---

ee/WFLY-19062-[PREVIEW]-Support_for_Jakarta_MVC_2.1.adoc

https://issues.redhat.com/browse/WFLY-19062

[WFLY-19062][Preview] Support for Jakarta MVC 2.1

---

elytron/WFLY-16793-oidc-identity-propagation.adoc

https://issues.redhat.com/browse/WFLY-16793

[WFLY-16793] Support for identity propagation within an EAR and across EARs with OIDC

---

messaging/WFLY-18000_Add_an_attribute_to_be_able_to_configure_max-read-page-bytes.adoc

* Adding a new attribute to AddressSetting.
Jira: https://issues.redhat.com/browse/WFLY-18000

[WFLY-18000]: Add an attribute to be able to configure max-read-page-bytes.

---

security/WFCORE-5466_Remove_Legacy_Vault_Integration.adoc

https://issues.redhat.com/browse/WFCORE-5466

[WFCORE-5466] Analysis for the removal of legacy vault integration from WildFly Core and WildFly.

---

security/WFLY-14922_Remove_PicketLink_Subsystem.adoc

https://issues.redhat.com/browse/WFLY-14922
https://issues.redhat.com/browse/WFLY-15076

[WFLY-14922] Initial analysis for removing the PicketLink subsystem

---

console/HAL-1709_Start_servers_in_suspended_mode.adoc

https://issues.redhat.com/browse/HAL-1709

HAL-1709: Start stopped servers in suspended mode

---

elytron/ELY-2334-Provide-SSLContext-to-Apache-Artemis-JMS-client.adoc

Jira: https://issues.redhat.com/browse/EAP7-683

[WFLY-7232]: Provide SSLContext to Apache Artemis JMS client.

---

console/HAL-1594_Configure_X509_certificate_mapping.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1594

HAL-1594: Configure mapping of X509Certificate to the underlying identity

---

console/HAL-1593_Configure_certificate_authority_used_by_certificate-authority-account.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1593

HAL-1593: Configure certificate authority

---

console/HAL-1591_Configure_module_libraries_to_all_deployments.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1591

HAL-1591: Configure module libraries to all deployments

---

console/HAL-1590_Configure_SSL_Certificate_revocation_using_OCSP.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1590

HAL-1590: Configure OCSP in Elytron Trust Manager

---

console/HAL-1739_Add_support_for_new_encrypted_expression_resources.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1739

HAL-1739: Add support for new encrypted expression support

---

console/HAL-1595_Configure_support_for_TLS_13.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1595

HAL-1595: Configure support for TLS 1.3

---

console/HAL-1592_Configure_enhanced_audit_logging.adoc

Analysis document for https://issues.redhat.com/browse/HAL-1592

HAL-1592: Configure Enhanced Audit Logging

---

elytron/WFLY-16306-keycloak-saml-feature-pack.adoc

https://issues.redhat.com/browse/WFLY-16306

[WFLY-16306] Support for a Galleon feature pack to install the Keycloak Elytron SAML adapter

---

build/WFLY-16863_Std_configs_galleon_layers.adoc

Analysis for https://issues.redhat.com/browse/WFLY-16863

WFLY-16863, std configs expressed with layers phase 1

---

microprofile/WFLY-17156-MicroProfile-Telemetry.adoc

[WFLY-17156] Implement Support for MicroProfile Telemetry

---

quickstarts/WFLY-17549_Migrate_Quickstarts_to_JakartaEE10.adoc

Issue: https://issues.redhat.com/browse/WFLY-17549

[WFLY-17549] Migrate Quickstarts to Jakarta EE 10

---

observability/WFLY-17144-add-micrometer-support.adoc

Add analysis document
https://issues.redhat.com/browse/WFLY-17144

[WFLY-17144] Add Micrometer support to WildFly

---

microprofile/WFLY-17138-convert-mp-metrics-subsystem-to-legacy-subsystem.adoc

https://issues.redhat.com/browse/WFLY-17138
Add analysis doc

[WFLY-17138] Convert MP Metrics subsystem to Admin-Only Mode

---

microprofile/WFLY-17992-delete-rhosak-from-mp-rm.adoc

https://issues.redhat.com/browse/WFLY-17992

[WFLY-17992] Remove RHOSAK support from MicroProfile Reactive Messaging

---

boms/WFLY-18526_Move_BOMs_to_the_Server_Repository.adoc

Issue: https://issues.redhat.com/browse/WFLY-18526

[WFLY-18526] adds proposal to move BOMs to the Server source repository

---

provisioning/WFLY-18671_Galleon_tooling_upward_compat.adoc

Issue: https://issues.redhat.com/browse/WFLY-18671

Proposal for WFLY-18671, WildFly Galleon Provisioning tooling should be upward compatible

---

.github/workflows/check_process.yml

[Issue_603] Use Ruby 3.2 in the check-proposals workflow

---

core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc

This file isn't rendering as expected on docs.wildfly.org/wildfly-proposals. So I'm tweaking it in a trivial way to spark a re-render.

Trivial change to trigger site republish

---

design-doc-template.adoc

The changes fix the comments in order to be YAML compatible, feel free to push back if it should be kept as is for higher visibility reasons.

Fixing comments in the YAML based header table

---

scripts/WFCORE-6935-system-daemon-scripts.adoc

Jira issue: https://issues.redhat.com/browse/WFCORE-6935
Fixes #614

[WFCORE-6935] Improve systemd service units

---

FEATURE_PROCESS.adoc

[Issue_675] Add a TOC to the FEATURE_PROCESS document

---

.github/workflows/jekyll.yml

Update GitHub action

---

design-doc-template.adoc

- Rework wording around promotes to promoted-by for clarity 
- General document clean up (normalizing line lengths, etc)

Template update

---

messaging/WFLY-20512_expose_scale_down_commit_interval.adoc

Jira: https://issues.redhat.com/browse/WFLY-20512
Issue: https://github.com/wildfly/wildfly-proposals/issues/709

[WFLY-20512]: Expose Artemis commit-interval attribute for scaledown.

---

_sass/layouts/post.scss

This fixes #714 
Before: http://docs.wildfly.org/wildfly-proposals/cli/WFCORE-4227-Add_the_ability_for_the_CLI_SSL_security_commands_to_be_able_to_obtain_a_server_certificate_from_Lets_Encrypt.html
After: https://jmesnil.github.io/wildfly-proposals/cli/WFCORE-4227-Add_the_ability_for_the_CLI_SSL_security_commands_to_be_able_to_obtain_a_server_certificate_from_Lets_Encrypt.html
@bstansberry Is that ok for you?

Reduce font size of the posts' title
